project/project_ecommerce/project_ecommerce/Areas/Admin/Controllers/hbController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using project_ecommerce.EDM;

namespace project_ecommerce.Areas.Admin.Controllers
{
    public class hbController : Controller
    {
        EcommerceEntities1 e = new EcommerceEntities1();
        // GET: Admin/hb
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(e.products.Find(id));
        }
        [HttpPost]
        public ActionResult Edit(product obj, HttpPostedFileBase product_img1)
        {
            if (product_img1 != null)
            {
                string filename = Path.GetFileName(product_img1.FileName);
                string fullpath = Path.Combine(Server.MapPath("~/Docs"), filename);
                product_img1.SaveAs(fullpath);
                obj.product_img1 = filename;


            }

            e.Entry(obj).State = System.Data.Entity.EntityState.Modified;
            e.SaveChanges();
            return RedirectToAction("ManageProducts");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(e.products.Find(id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Deletehb(int id)
        {
            e.products.Remove(e.products.Find(id));
            e.SaveChanges();
            return RedirectToAction("ManageProducts");
        }

        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(FormCollection fc)
        {
            string email = fc["email"];
            string pass = fc["password"];

            var Adminobj = e.admins.Where(u => u.email == email && u.password == pass).FirstOrDefault();
            if (Adminobj != null)
            {
                Session["userID"] = Adminobj.admin_id;
                Session["username"] = Adminobj.fname;
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.loginerror = "invalid email or password";
            }
            return View();
        }

        public ActionResult logout()
        {
            Session.Abandon();
            Session.Clear();
            return RedirectToAction("login");
        }

        public ActionResult ManageProducts()
        {
            return View(e.products.ToList());
        }
        [HttpGet]
        public ActionResult addproduct()
        {
            return View();
        }
        [HttpPost]
        public ActionResult addproduct(product obj , HttpPostedFileBase product_img1)
        {
            if(product_img1 != null)
            {
                string filename = Path.GetFileName(product_img1.FileName);
                string fullpath = Path.Combine(Server.MapPath("~/Docs"), filename);
                product_img1.SaveAs(fullpath);
                obj.product_img1 = filename;


            }
            e.products.Add(obj);
            e.SaveChanges();
            return RedirectToAction("ManageProducts");
        }
    }
}

project/project_ecommerce/project_ecommerce/Areas/Admin/Views/hb/Delete.cshtml
@model project_ecommerce.EDM.product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/admin_LayoutPage1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_quentity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_quentity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_img1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_img1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_img2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_img2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product_img3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_img3)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "ManageProducts")
        </div>
    }
</div>

project/project_ecommerce/project_ecommerce/Areas/Admin/Views/hb/Edit.cshtml
@model project_ecommerce.EDM.product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/admin_LayoutPage1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "hb", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.product_id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.product_id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.product_quentity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.product_quentity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.product_quentity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.product_img1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="product_img1" id="product_img1" class="form-control" />
            @Html.ValidationMessageFor(model => model.product_img1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
            @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.product_img2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_img3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img3, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ManageProducts")
</div>

project/project_ecommerce/project_ecommerce/Areas/Admin/Views/hb/ManageProducts.cshtml
@model IEnumerable<project_ecommerce.EDM.product>

@{
    ViewBag.Title = "ManageProducts";
    Layout = "~/Areas/Admin/Views/Shared/admin_LayoutPage1.cshtml";
}

    <h2>ManageProducts</h2>
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.product_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_quentity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_img1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_img2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product_img3)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.product_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product_quentity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product_img1)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.product_img2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product_img3)
                </td>*@
                <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.product_id }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.product_id  })
                </td>
            </tr>
        }

    </table>

project/project_ecommerce/project_ecommerce/Areas/Admin/Views/hb/addproduct.cshtml
@model project_ecommerce.EDM.product

@{
    ViewBag.Title = "addproduct";
    Layout = "~/Areas/Admin/Views/Shared/admin_LayoutPage1.cshtml";
}

<script src="~/bvalidator/jquery.bvalidator.js"></script>

<script src="~/bvalidator/themes/presenters/bs3form.min.js"></script>
<script src="~/bvalidator/themes/bs3/bs3form/bs3form.js"></script>
<link href="~/bvalidator/bValidator2.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {
        $('#frm').bValidator();
    });
</script>

<h2>Addproduct</h2>
<div class="container">
    <div class="col-md-6">
        @using (Html.BeginForm("addproduct", "hb", FormMethod.Post, new { @id = "frm", @enctype = "multipart/form-data"}))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @*<h4>product</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
                    @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.product_quentity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.product_quentity, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
                    @Html.ValidationMessageFor(model => model.product_quentity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
                    @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control", @databvalidator = "required" } })
                    @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.product_img1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="product_img1" id="product_img1" class="form-control" />
                    @Html.ValidationMessageFor(model => model.product_img1, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
            @Html.LabelFor(model => model.product_img2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_img3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_img3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_img3, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "ManageProducts")
        </div>
    </div>
</div>

project/project_ecommerce/project_ecommerce/Areas/Admin/Views/hb/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>login</title>

    <title>Shoppy an Admin Panel Category Flat Bootstrap Responsive Website Template | Login :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <link href="~/Areas/Admin/web/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <!-- Custom Theme files -->
    <link href="~/Areas/Admin/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!--js-->
    <script src="~/Areas/Admin/web/js/jquery-2.1.1.min.js"></script>
    <!--icons-css-->
    <link href="~/Areas/Admin/web/css/font-awesome.css" rel="stylesheet">
    <!--Google Fonts-->
    <link href='//fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Work+Sans:400,500,600' rel='stylesheet' type='text/css'>
    <!--static chart-->

</head>
<body>
    <div class="login-page">
        <div class="login-main">
            <div class="login-head">
                <h1>Login</h1>
            </div>
            <div class="login-block">
                @using (Html.BeginForm())
                {
                    <input type="text" name="email" placeholder="Email" required="">
                    <input type="password" name="password" class="lock" placeholder="Password">
                    <div class="forgot-top-grids">
                        <div class="forgot-grid">
                            <ul>
                                <li>
                                    <input type="checkbox" id="brand1" value="">
                                    <label for="brand1"><span></span>Remember me</label>
                                </li>
                            </ul>
                        </div>
                        <div class="forgot">
                            <p><span style="color:black;">@ViewBag.loginerror</span></p>
                            <a href="#">Forgot password?</a>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <input type="submit" name="Sign In" value="Login">
                    <h3>Not a member?<a href="signup.html"> Sign up now</a></h3>
                    <h2>or login with</h2>
                    <div class="login-icons">
                        <ul>
                            <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="google"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                }
                <h5><a href="index.html">Go Back to Home</a></h5>
            </div>
        </div>
    </div>
</body>
</html>